### PR TITLE
DOCS: Fix delete response content everywhere

### PR DESCRIPTION
**Pull request by nir0s**
Our response to DELETE calls is actually not what's currently mentioned in the docs, but rather a 204. This is also stated in the intro, but then inconsistently reported in all other docs.

### CODE REVIEW

**Review by holograph — APPROVED** [review]
I’m assuming our docs are out of date?

**Comment by nir0s** [comment]
What do you mean? In general? No, they're very up-to-date.

**Comment by holograph** [comment]
I meant with respect to the return values for such calls... was the API changed? I'm just curious where this is coming from, as no context was provided in the description...

**Comment by nir0s** [comment]
Oh, no.. nothing changes. Re:description, it's in the issue, and so stupid, that I simply skipped it here, but I should provide some context here.

**Pull request merged**
